### ISSUE TITLE
Got errors on first call

### ISSUE THREAD

**Issue by Spr-Aachen** [zackees/static_ffmpeg#10]
Sorry to interrupt, I'm using win64 platform and I got several errors while executing the 'static_ffmpeg -i file.mp4 ...' command for first call.
```
Traceback (most recent call last):
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000016F50747A60>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /zackees/ffmpeg_bins/main/v5.0/win32.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016F50747A60>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Projekt\AI\Anaconda3\envs\My_Env\Scripts\static_ffmpeg.exe\__main__.py", line 7, in <module>
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\static_ffmpeg\run.py", line 125, in main_static_ffmpeg
    ffmpeg_exe, _ = get_or_fetch_platform_executables_else_raise()
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\static_ffmpeg\run.py", line 69, in get_or_fetch_platform_executables_else_raise
    return _get_or_fetch_platform_executables_else_raise_no_lock(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\static_ffmpeg\run.py", line 93, in _get_or_fetch_platform_executables_else_raise_no_lock
    download_file(url, local_zip)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\static_ffmpeg\run.py", line 51, in download_file
    with requests.get(url, stream=True) as req:
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "d:\Projekt\AI\Anaconda3\envs\My_Env\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /zackees/ffmpeg_bins/main/v5.0/win32.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016F50747A60>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
```
I've checked my network and it's working fine. Any solutions?

**Comment by zackees** [comment]
I've never seen this happen before with static_ffmpeg.

I have seen something similar happen before with my computer, where the command line would return an error but the web browser would connect just fine. It turned out to be an issue with the dns entries on windows.

Can you try and run a `ping` from the terminal? I bet that will fail also, as will running `curl`.

This is what fixed it for me
```
ipconfig /flushdns
ipconfig /release
ipconfig /renew
```

**Comment by Spr-Aachen** [comment]
Solve my problems, thank you sir!
